shellmancer/game/routes.py
from flask import Blueprint, request, render_template, url_for, redirect, flash
from flask_login import current_user, login_required
from shellmancer import db, ph
from shellmancer.models import SinglePlayerCampaign, CharacterSheet
from shellmancer.game.forms import NewCampaignForm, CampaignSettingsForm
from shellmancer.auth.forms import RegisterForm
from shellmancer.models import UserAccount
from shellmancer.auth.utils import send_verify_email


game = Blueprint('game', 'shellmancer')


@game.route('/campaign/new', methods=['GET', 'POST'])
@login_required
def new_campaign():
    if not current_user.gamemaster.access > 0:
        return redirect(url_for('users.player_profile'))
    else:
        form = NewCampaignForm()
        if form.validate_on_submit():
            campaign = SinglePlayerCampaign(name=form.title.data,
                                            descrip=form.descrip.data,
                                            gamemaster_id=current_user.gamemaster.id)
            db.session.add(campaign)
            db.session.commit()
            return redirect(url_for('game.campaign_settings', camp_id=campaign.id))
    return render_template("campaign_new.html",
                           form=form, title="New Campaign")


@game.route('/campaign/<camp_id>/update', methods=['GET', 'POST'])
@login_required
def campaign_settings(camp_id):
    try:
        campaign = SinglePlayerCampaign.query.get(camp_id)
    except:
        flash('This campaign does not exist.', 'info')
        return redirect(url_for('game.all_campaigns'))

    if current_user.gamemaster.id != campaign.gamemaster.id:
        return redirect(url_for('game.campaign_profile', camp_id=camp_id))

    else:
        form = CampaignSettingsForm()
        if form.validate_on_submit():
            campaign.name = form.title.data
            campaign.descrip = form.descrip.data
            campaign.intro_text = form.intro_text.data
            campaign.attr_a_name = form.attr_a_name.data
            campaign.attr_b_name = form.attr_b_name.data
            campaign.attr_c_name = form.attr_c_name.data
            campaign.attr_a_descrip = form.attr_a_descrip.data
            campaign.attr_b_descrip = form.attr_b_descrip.data
            campaign.attr_c_descrip = form.attr_c_descrip.data
            campaign.has_adult_content = form.has_adult_content.data
            db.session.commit()
        elif request.method == 'GET':
            form.title.data = campaign.name
            form.descrip.data = campaign.descrip
            form.intro_text.data = campaign.intro_text
            form.attr_a_name.data = campaign.attr_a_name
            form.attr_b_name.data = campaign.attr_b_name
            form.attr_c_name.data = campaign.attr_c_name
            form.attr_a_descrip.data = campaign.attr_a_descrip
            form.attr_b_descrip.data = campaign.attr_b_descrip
            form.attr_c_descrip.data = campaign.attr_c_descrip
    return render_template("campaign_settings.html", form=form, campaign=campaign,
                           title=f"Settings '{campaign.name}'")


@game.route('/campaign')
@login_required
def all_campaigns():
    # Temporary Redirect Away From Campaign List
    if True:
        flash("For now, the campaign directory redirects here. It's the only campaign afterall.", "secondary")
        return redirect(url_for("game.campaign_profile", camp_id=1))

    # campaigns = SinglePlayerCampaign.query.all()
    # campaigns.reverse()
    # return render_template('campaigns.html',
    #                        title="All Campaigns", campaigns=campaigns, context="ALL")



@game.route('/campaign/<camp_id>')
@login_required
def campaign_profile(camp_id):
    try:
        campaign = SinglePlayerCampaign.query.get(camp_id)
        characters = CharacterSheet.query.filter_by(
            campaign_id=camp_id, player_id=current_user.player.id).all()
    except AttributeError:
        return redirect(url_for('main.docs'))

    if len(characters) < 1:
        flash("You do not have any characters for this campaign yet. Make one!", "info")

    return render_template('campaign_profile.html',
                           title=f"Campaign | {campaign.name}", campaign=campaign, character_count=len(characters),
                           pfp=f"img/pfp/{campaign.gamemaster.user.image_file}")


@game.route('/campaign/<camp_id>/delete')
@login_required
def campaign_delete(camp_id):
    try:
        campaign = SinglePlayerCampaign.query.get(camp_id)
    except:
        flash('This campaign does not exist.', 'info')
        return redirect(url_for('game.all_campaigns'))
    if current_user.id == campaign.gamemaster_id:
        db.session.delete(campaign)
        db.session.commit()
        flash("Campaign has been deleted", 'success')
        return redirect(url_for('game.campaign_profile', camp_id=camp_id))
    flash("You cannot delete a campaign that does not belong to you", 'warning')
    return redirect(url_for('game.campaign_profile', camp_id=camp_id))



@game.route('/campaign/<camp_id>/new', methods=['GET', 'POST'])
def new_character(camp_id):
    campaign = SinglePlayerCampaign.query.get(camp_id)

    if not campaign:
        return redirect(url_for("game.all_campaigns"))

    if not current_user.is_authenticated:
        flash("You are viewing a limited preview of this site without an account. You'll need one to save.", "danger")
        form = RegisterForm()

        if form.validate_on_submit():
            hashed_pw = ph.hash(form.password.data)
            user = UserAccount(email=form.email.data, password=hashed_pw)

            db.session.add(user)
            db.session.commit()

            send_verify_email(user)

            flash(f"Account created for {form.email.data}"
                  + "Check your email to verify account for full functionality. You may login now.", 'success')
            return redirect(url_for('auth.login'))
    else:
        form = None
    # flash("You will lose any progress if you navigate away from this page without submitting.", "danger")

    return render_template("character_new.html", campaign=campaign, form=form)




@game.route('/campaign/<camp_id>/characters/')
@login_required
def campaign_characters(camp_id):
    try:
        campaign = SinglePlayerCampaign.query.get(camp_id)
    except:
        flash('This campaign does not exist.', 'info')
        return redirect(url_for('game.all_campaigns'))


    return render_template("campaign_characters.html", characters=characters,
                           title=f"Characters for {campaign.name}", campaign=campaign)




@game.route('/campaign/<camp_id>/popup')
def campaign_popup(camp_id):
    try:
        campaign = SinglePlayerCampaign.query.get(camp_id)
    except:
        flash("That campaign does not exist", "info")
        return redirect(url_for('game.all_campaigns'))

    return render_template('campaign_popup.html', campaign=campaign)

shellmancer/templates/campaign_characters.html
{% extends 'base.html' %}

{% block sidebar %}
  {% if current_user.id != campaign.gamemaster.user.id %}
    {% include 'player_side.html' %}
  {% endif %}
  {% include 'campaign_side.html' %}
{% endblock %}

{% block content %}

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Attributes</th>
      <th scope="col">Devices</th>
      <th scope="col">Contacts</th>
    </tr>
  </thead>
  <tbody>
    <tr class="table-active">
      <th scope="row"></th>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

<div class="card">
 <div class="card-body">
  <h2 class="card-title text-success">{{ campaign.name }}</h2>
   <h6 class="card-subtitle mb-2 text-muted">{{ campaign.descrip }}</h6>
   <hr>
   <div class="tab-content">
    <div id="one" class="card-text tab-pane fade show active"></div>
    <div id="two" class="card-text tab-pane fade"></div>
   </div>

     </div>
   </div>



{% endblock %}

{% block buttons %}
        <a href="#">
            <div class="btn btn-success" data-toggle="modal" data-target="#characterWizard1">
              Make Character
            </div>
        </a>

  <script src="{{ url_for('static', filename='js/randombars.js') }}"></script>

{% endblock %}

shellmancer/templates/campaign_list.html
<hr>
{% for campaign in campaigns %}
  <div class="card">
    <div class="card-body">
      <h4>
        <a class="text-success" href="{{ url_for('game.campaign_profile', camp_id=campaign.id) }}">
          {{campaign.name}}
        </a>
      </h4>
       <small>
         <strong>Gamemaster:</strong>
          <em>{{ campaign.gamemaster.user.user_name }}</em> </br>
         <strong>Players:</strong>
  <!--        <em></em> </br>-->
       </small>
      {{ campaign.descrip }} </br>
    </div>
  </div>
<hr>
{% endfor %}

shellmancer/templates/campaign_popup.html
THIS IS A TEST

shellmancer/templates/campaign_profile.html
{% extends 'base.html' %}

{% block sidebar %}
 {% include 'campaign_side.html' %}
 {% if current_user.id != campaign.gamemaster.user.id %}
<!--    {% include 'player_side.html' %}-->
  {% endif %}


{% endblock %}

{% block content %}
<div class="card">
 <div class="card-body">
  <h2 class="card-title text-success">{{ campaign.name }}</h2>
   <h6 class="card-subtitle mb-2 text-muted">{{ campaign.descrip }}</h6>
   <hr>
   <div class="tab-content">
    <div id="one" class="card-text tab-pane fade show active">
      <p>It’s present day -- right the fuck now. You are just another disenfranchised-class, no-name,
         nothing-special-to-him-or-her, get-a-shell-or-die-trying hacker.</p>
      <p>Guess what? You just lost your job, and we’re living in meatspace. Do you know what that’s like, really? I
         mean sure, you've been down here before, but we're real deep into meatspace right now. You know how it’s
         different for jobless people like us?</p>
      <p>There’s no cloud virtualization reality server to go back to when the party’s over. You want to judge me
         from the neural net? I can’t even login to my own name. And now neither can you.</p>
      <p>So let’s see how far you can get out of this cesspool and back to verified status to operate in the
         confines of the corporate fucking rule of this planet -- where everything worth living for exists in
         geocentric orbit with trash, debris, and the view of Earth from up <em>here</em> behind so much cloudy dust and
         bullshit you can’t even really see how bad it is down <em>there</em>.</p>
      <p>Correction: Down <em>here</em>, motherfucker. Check your privilege -- you ain’t got none anymore. This is
         where we live. This is how we live.</p>
      <p>This isn’t what you want to do. And this isn’t what you plan to do.</p>
      <p>Stick around, kid. You’re not going to find the typical cyberpunk classes and roles to play here. You are a
         hacker. You’re just another one. We’re all hackers.</p>
      <p>Let’s see what’s going to happen real quick if you’re not.</p>
    </div>

   <div id="two" class="card-text tab-pane fade">
   <h4 class="text-info">What’s your character’s name?</h4>
   <p>Oh, wait...</p>
   <p>That’s a perk you don’t get at starting level.
     <span class="text-success">Let’s talk about your new email address.</span></p>
   <p>Yeah, the new one. You think you’re just going to log back into a Virtico account down here? Shit. That’s a
          god damn laugh I needed.</p>
   <p>Bitch, where you gonna make your email account at? Where you gonna type in the address to their node on
          what interface with what network? I don’t even want your cool hacker name, bitch.</p>
   <p>You namesless, kid. Just Another Shell Hacker. Remember that.</p>
    </div>
   </div>

     </div>
   </div>

{% endblock %}

{% block buttons %}
  {% include 'campaign_buttons.html' %}
{% endblock %}

shellmancer/templates/campaigns.html
{% extends 'base.html' %}

{% block sidebar %}
  {% include 'player_side.html' %}
{% endblock %}

{% block content %}
  {% include 'campaign_list.html' %}
{% endblock %}

{% block buttons %}

{% endblock %}

shellmancer/templates/character_new2.html
{% extends 'base.html' %}

{% block morestyle %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fork-awesome@1.1.7/css/fork-awesome.min.css"
  integrity="sha256-gsmEoJAws/Kd3CjuOQzLie5Q3yshhvmo7YNtBG7aaEY=" crossorigin="anonymous">
{% endblock %}

{% block sidebar %}
  {% if not current_user.is_authenticated %}

  {% endif %}
{% endblock %}

{% block collapse %}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-item nav-link" href="#">
    {% if show_game_icons %}
      <i class="fa fa-play-circle fa-lg" aria-hidden="true"></i>
    {% endif %}
    {% if show_game_labels %}
      <span class="">Plays</span>
    {% endif %}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
     {% for item in icon_label_button_html %}
        {{item|safe}}
     {% endfor %}
    </ul>
  </div>
</nav>

{% endblock %}

{% block content %}




<div class="jumbotron">

  <div class="tab-content">
    <div id="one" class="card-text tab-pane fade show active">

      <div class="center">
        <h4 class="font-inline">
          Spend <span id="remaining-points" class="text-info"></span> points on primary attributes. </h4>
      </div>

      <hr class="my-4">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <h5 class="font-orbitron ml-5">
              meat: <span id="attribute-one" class="text-danger font-inline display"></span>
            </h5>
          </div>
        </div>
        <div class="row">
          <div class="col-2">
            <div class="btn btn-sm center btn-primary" onclick="reducePoints(getWizardBar1, attr1)">
              <i class="fa fa-minus fa-sm" aria-hidden="true"></i>
            </div>
          </div>
          <div class="col-8">
            <div class="progress bg-primary" id="wizardProgress1">
              <div class="progress-bar progress-bar-striped progress-bar-animated bg-danger" id="wizardBar1"
                   role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="width: 10%"></div>
            </div>
          </div>
          <div class="col-2">
            <div class="btn btn-sm center btn-primary" onclick="increasePoints(getWizardBar1, attr1)">
              <i class="fa fa-plus fa-sm" aria-hidden="true"></i>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-12">
            <h5 class="font-orbitron ml-5">
              l33t: <span id="attribute-two" class="text-success font-inline"></span>
            </h5>
          </div>
        </div>
        <div class="row">
          <div class="col-2">
            <div class="btn btn-sm center btn-primary" onclick="reducePoints(getWizardBar2, attr2)">
              <i class="fa fa-minus fa-sm" aria-hidden="true"></i>
            </div>
          </div>
          <div class="col-8">
            <div class="progress bg-primary" id="wizardProgress2">
              <div class="progress-bar progress-bar-striped progress-bar-animated bg-success" id="wizardBar2"
                   role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="width: 10%"></div>
            </div>
          </div>
          <div class="col-2">
            <div class="btn btn-sm center btn-primary" onclick="increasePoints(getWizardBar2, attr2)">
              <i class="fa fa-plus fa-sm" aria-hidden="true"></i>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-12">
            <h5 class="font-orbitron ml-5">
              street: <span id="attribute-three" class="text-purple font-inline"></span>
            </h5>
          </div>
        </div>
        <div class="row">
          <div class="col-2">
            <div class="btn btn-sm center btn-primary" onclick="reducePoints(getWizardBar3, attr3)">
              <i class="fa fa-minus fa-sm" aria-hidden="true"></i>
            </div>
          </div>
          <div class="col-8">
            <div class="progress bg-primary" id="wizardProgress3">
              <div class="progress-bar progress-bar-striped progress-bar-animated bg-purple" id="wizardBar3"
                   role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="width: 10%"></div>
            </div>
          </div>
          <div class="col-2">
            <div class="btn btn-sm center btn-primary" onclick="increasePoints(getWizardBar3, attr3)">
              <i class="fa fa-plus fa-sm" aria-hidden="true"></i>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div id="two" class="card-text tab-pane fade">

      <div class="center">
        <h4 class="font-inline">
          sdfdsfdsafdsfdsafdsafdsf
        </h4>
      </div>

      <hr class="my-4">
      <div class="container"></div>
    </div>

    
    <div id="three" class="card-text tab-pane fade">

      <div class="center">
        <h4 class="font-inline">
          You Have <span class="text-info"">2</span> Things to Your Name... </h4>
      </div>
      <hr class="my-4">
      <div class="container font-quantico">
        <div class="row">

          <div class="col-6">
            <div class="card devices" id="device-one">
              <div class="card-body">
                <h4 class="card-title option-title font-quantico">Stolen Cyberdeck</h4>
                <h6 class="card-subtitle mb-2 text-muted">+1 street / -1 leet</h6>
                <p class="card-text">Can't say for sure where it came from, but it's got...
                                     somebody's shit on it. You can't seem to wipe it clean. Maybe it's got something useful.
                                     Hey, it's yours now.</p>

              </div>
            </div>
          </div>

          <div class="col-6">
            <div class="card devices" id="device-two">
              <div class="card-body">
                <h4 class="card-title option-title font-quantico">Samurai Sword</h4>
                <h6 class="card-subtitle mb-2 text-muted">+1 meat / -1 street</h6>
                <p class="card-text">"Hey, you seen that cat with the sword on 16th and Commerce? Nah, fuck that. We bouta find
                                     another corner. That's his corner." Ain't no body fuck with you.</p>
              </div>
            </div>
          </div>

        </div>

        <div class="row mt-4">

          <div class="col-6">
            <div class="card devices" id="device-three">
              <div class="card-body">
                <h4 class="card-title option-title font-quantico">85.44 GB Wordlist</h4>
                <h6 class="card-subtitle mb-2 text-muted">+1 leet / -1 meat</h6>
                <p class="card-text">A prolific assembly of words like "123456 password iloveyou babygirl," all organized
                                     by demographic users: porn_addicts, sports_fans, script_kids.</p>
              </div>
            </div>
          </div>

          <div class="col-6">
            <div class="card devices" id="device-four">
              <div class="card-body font-quantico">
                <h4 class="card-title option-title font-quantico">Fake Work Visa</h4>
                <h6 class="card-subtitle mb-2 text-muted">+1 street / -1 meat</h6>
                <p class="card-text">"You know, my dad worked for Vertico for 25 years. It's a good company. You're not
                                     supposed to be here this time of night, but... you have a good night, sir." </p>
              </div>
            </div>
          </div>

        </div>

      </div>

    </div>
  </div>

  <p class="lead">
    <a id="character-submit" class="btn btn-primary btn-lg default-off" href="#" role="button">Learn more</a>
  </p>
</div>

<!---->

<a href="https://www.google.com">
  <div id="next-button" class="btn default-off text-right">fsfgdsfgdg</div>
</a>


{% endblock %}

{% block buttons %}
  {% include 'character_new_side.html' %}
{% endblock %}

{% block modals %}
  {% include 'character_wizard_modals.html' %}
{% endblock %}

{% block morescript %}
<script src="{{ url_for('static', filename='js/spendpoints.js') }}"></script>
<!-- <script src="{{ url_for('static', filename='js/dist/tstest.js') }}"></script> -->
{% endblock %}

shellmancer/templates/character_wizard_modals.html
<!-- Modal Dialog  characterWizard1 -->
<div class="modal fade" id="characterWizard1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header bg-dark">
        <h5 class="modal-title">Character Creation Wizard</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body bg-primary">
        <p>
           You will be given a series of choices to make, the first of which will be how to allocate your primary
           attributes.</p>
<p></p>

        <div class="progress" id="wizardProgress">
          <div class="progress-bar progress-bar-striped progress-bar-animated bg-danger" id="wizardBar1"
               role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="width: 65%"></div>
        </div>

        <div class="progress" id="wizardProgress2">
          <div class="progress-bar progress-bar-striped progress-bar-animated bg-success" id="wizardBar2"
               role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="width: 15%"></div>
        </div>


        <div class="progress" id="wizardProgress3">
          <div class="progress-bar progress-bar-striped progress-bar-animated bg-purple" id="wizardBar3"
               role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="width: 40%"></div>
        </div>

        <p>As expected, they represent physical prowess, mental accuity, and social abilities. This is nothing new for a role playing game. Let's have a look at these values.</p>



      </div>
      <div class="modal-footer bg-dark">
<!--        <button type="button" class="btn btn-sm btn-primary" >Save changes</button>-->
        <a class="btn btn-sm btn-secondary"
           href="{{ url_for('game.new_character', camp_id=campaign.id) }}">Ready!</a>

      </div>
    </div>
  </div>
</div>



<!-- Modal Dialog  characterWizard2 -->
<div class="modal" id="characterWizard2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header bg-dark">
        <h5 class="modal-title">Character Creation Wizard</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body bg-primary">
        <p>You just lost your job.</p>




        <div class="progress">
          <div class="progress-bar progress-bar-striped progress-bar-animated bg-purple" role="progressbar"
               aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%"></div>
        </div>
      </div>
      <div class="modal-footer bg-dark">
<!--        <button type="button" class="btn btn-sm btn-primary" >Save changes</button>-->
        <button type="button" class="btn btn-sm btn-secondary"
                data-toggle="modal" data-target="#characterWizard2">Next</button>

      </div>
    </div>
  </div>
</div>

shellmancer/templates/docs_left.html
<div class="card border-purple text-light bg-dark mb-2">
  <div class="card-header text-center text-info"><h4>Documentation</h4></div>
  <div class="card-body bg-primary">


<ul class="list-group">
  <li class="list-group-item d-flex justify-content-between align-items-center">
    The Prototype Campaign
    <span class="badge badge-primary badge-pill">1</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    The Campaign Setting Specification
    <span class="badge badge-primary badge-pill">2</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    Shell Design and Game Building
    <span class="badge badge-primary badge-pill">1</span>
  </li>
</ul>

      <p class="card-text"></p>
  </div>
</div>

shellmancer/templates/menu.html
<div id="top-nav" class="fixed-top">
  <ul class="top-nav nav-tabs bg-primary container-fluid">

    <!-- Account Dropdown -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true"
         aria-expanded="false" href="#">
        Account
      </a>

      <div class="dropdown-menu bg-dark">
        <div id="account-menu-div">
          {% if not current_user.is_verified %}
          <a id="account-menu-get-verified" class="dropdown-item" href="{{ url_for('auth.verify_request') }}">
            <strong><span class="text-warning">Get Verified</span></strong>
          </a>
          {% endif %}

          <a id="account-menu-player-profile" class="dropdown-item" href="{{ url_for('users.player_profile') }}">
            <span>Player Profile</span>
          </a>

          {% if current_user.gamemaster.access > 0 %}
          <a id="account-menu-gm-profile" class="dropdown-item inactive"
             href="{{ url_for('users.gamemaster_profile') }}">
            <span>GameMaster Profile</span>
          </a>
          {% endif %}

          <a id="account-menu-settings" class="dropdown-item" href="{{ url_for('users.user_settings') }}">
            <span>Settings</span>
          </a>

          <a id="account-menu-logout" class="dropdown-item" href="{{ url_for('auth.logout') }}">
            <span>Logout</span>
          </a>
        </div>
      </div>
    </li>

    <!-- View Dropdown Button -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
         aria-expanded="false" href="#">
        Browse
      </a>

      <div class="dropdown-menu bg-dark">
        <div id="browse-menu-div" class="inactive">
          <a id="browse-menu-campaigns" class="dropdown-item" href="{{ url_for('game.all_campaigns') }}">
            <span>Campaigns</span>
          </a>

          <a id="browse-menu-open-link" class="dropdown-item" href="#">
            <span>Characters</span>
          </a>

          <a id="browse-menu-corps" class="dropdown-item" href="#">
            <span>Corporations</span>
          </a>

          <a id="browse-menu-contacts" class="dropdown-item" href="#">
            <span>Contacts</span>
          </a>

          <a id="browse-menu-locales" class="dropdown-item" href="#">
            <span>Places</span>
          </a>

        </div>
      </div>
    </li>

    <!-- View Dropdown Button -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
         aria-expanded="false">
        View
      </a>

      <div class="dropdown-menu bg-dark">
        <div id="view-menu-div" class="inactive">
          <a id="open-terminal" class="dropdown-item" href="#">
            <span id="terminal-option-listing-open">Open Terminal</span>
            <span id="terminal-option-listing-close" class="default-off">Close Terminal</span>
          </a>
        </div>
      </div>
    </li>

    <!-- Tools Dropdown -->
    <!--<li class="nav-item dropdown">-->
    <!-- <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">-->
    <!--   Tools-->
    <!-- </a>-->

    <!-- <div class="dropdown-menu bg-dark">-->
    <!--   <a id="open-terminal" class="dropdown-item" href="#">-->
    <!--    <span id="terminal-option-listing-open">Open Terminal</span>-->
    <!--    <span id="terminal-option-listing-close" class="default-off">Close Terminal</span>-->
    <!--   </a>-->
    <!-- </div>-->
    <!--</li>-->

    <!-- Help Dropdown -->
    <!--<li class="nav-item dropdown">-->
    <!-- <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">-->
    <!--   Help-->
    <!-- </a>-->

    <!--  &lt;!&ndash; Dropdown 1  &ndash;&gt;-->
    <!--   <div class="dropdown-menu bg-dark">-->
    <!--    <a id="help-menu-docs" class="dropdown-item" href="{{ url_for('main.docs') }}">-->
    <!--      <span>Documentation</span>-->
    <!--    </a>-->
    <!--    <a id="help-menu-about" class="dropdown-item" href="#">-->
    <!--      <span>About</span>-->
    <!--    </a>-->
    <!--   </div>-->

<!--    </li>-->
  </ul>
</div>